imports:
  - config.yaml

parameters:
  daipeproject:
    databricks:
      address: 'https://adb-8328309645514519.19.azuredatabricks.net/'
      repo:
        base_dir: "/Repos/{repo_name}/latest_tag"
      job:
        suffix: "{repo_name}"

  datalakebundle:
    notebook:
      display:
        enabled: False
