imports:
  - config.yaml

parameters:
  databricks:
    address: https://westeurope.azuredatabricks.net
    workspace:
      base_dir: '/__myproject__'

  datalakebundle:
    notebook:
      display:
        enabled: False
