imports:
  - config.yaml

parameters:
  daipeproject:
    databricks:
      address: 'https://adb-3461535502276712.12.azuredatabricks.net'
      repo:
        base_dir: "/Repos/{repo_name}/latest_tag"
      job:
        suffix: "{repo_name}"x

  datalakebundle:
    notebook:
      display:
        enabled: False
