imports:
  - config.yaml

parameters:
  daipeproject:
    databricks:
      address: 'https://adb-7591567723507203.3.azuredatabricks.net'
      repo:
        base_dir: "/Repos/{repo_name}/{branch_name}"
      job:
        suffix: "{repo_name} ({branch_name})"
