imports:
  - config.yaml

parameters:
  daipeproject:
    databricks:
      address: 'https://adb-8328309645514519.19.azuredatabricks.net/'
      repo:
        base_dir: "/Repos/{user_folder_name}/{dir_name}"
      job:
        suffix: "{user_folder_name} ({dir_name})"
