variables:
  # read main variables from infra variables definition
  - template: variables/variables.yml
  # defined variables
  # run number
  - name: Build.Version
    value:  $[counter(0)]
  # current branch name based on head
  - name: CURRENT_BRANCH
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/heads/') }}:
      value: $[ replace(variables['Build.SourceBranch'], 'refs/heads/', '') ]
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/pull/') }}:
      value: $[ replace(variables['System.PullRequest.SourceBranch'], 'refs/heads/', '') ]
    ${{ if startsWith(variables['Build.SourceBranch'], 'refs/tags/') }}:
      value: 'master'

# build name based on pipeline name, source branch, date and run number
name: "$(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd).$(Build.Version)"

trigger:
  branches:
    include:
      - master
      - feature-*
      - hotfix-*
      - refs/tags/*

stages:
  - stage: DataFactoryCI
    dependsOn: []
    displayName: Build & Test Data Factory
    jobs:
      - template: templates/datafactory-ci.yml

  - stage: DataFactoryCDdev
    displayName: Deploy Data Factory to dev environment
    dependsOn: DataFactoryCI
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    jobs:
      - template: templates/datafactory-cd.yml

  - stage: DataFactoryCDtest
    displayName: Deploy Data Factory to test environment
    dependsOn: DataFactoryCI
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: templates/datafactory-cd.yml

  - stage: DataFactoryCDprod
    displayName: Deploy Data Factory to prod environment
    dependsOn: DataFactoryCI
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - template: templates/datafactory-cd.yml

  - stage: DaipeCI
    dependsOn: []
    displayName: Build & Test Daipe
    jobs:
      - template: templates/daipe-ci.yml

  - stage: DaipeCDdev
    displayName: Deploy Daipe to dev environment
    dependsOn: DaipeCI
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - template: templates/daipe-cd.yml

  - stage: DaipeCDtest
    displayName: Deploy Daipe to test environment
    dependsOn: DaipeCI
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: templates/daipe-cd.yml

  - stage: DaipeCDprod
    displayName: Deploy Daipe to prod environment
    dependsOn: DaipeCI
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - template: templates/daipe-cd.yml