variables:
  # read main variables from infra variables definition
  - template: variables/variables.yml
  # defined variables
  # run number
  - name: Build.Version
    value:  $[counter(0)]

# build name based on pipeline name, source branch, date and run number
name: "$(BuildDefinitionName)_$(SourceBranchName)_$(date:yyyyMMdd).$(Build.Version)"

trigger:
  branches:
    include:
      - master
      - feature-*
      - hotfix-*
      - refs/tags/*

stages:
  - stage: Build
    dependsOn: []
    displayName: Build & Test Daipe
    jobs:
      - template: templates/build.yml

  - stage: DeployDev
    displayName: Deploy Daipe to dev environment
    dependsOn: Build
    condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/')))
    jobs:
      - template: templates/deploy.yml

  - stage: DeployTest
    displayName: Deploy Daipe to test environment
    dependsOn: Build
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest'))
    jobs:
      - template: templates/deploy.yml

  - stage: DeployProd
    displayName: Deploy Daipe to prod environment
    dependsOn: Build
    condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
    jobs:
      - template: templates/deploy.yml
