name: Branch delete pipeline
on:
  delete:

jobs:
  delete:
    uses: daipe-ai/daipe-project-ci-cd/.github/workflows/run_command.yml@v1
    with:
      command: daipe dbx:repo:delete --env=test --repo-name=${{ github.event.repository.name }} --branch=${{ github.event.ref }}
    secrets:
      DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
