name: Templates Creator Pipeline
on:
  push:
    branches:
      - master

jobs:
  create_templates:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

      - name: Setup git config
        run: |
          git config --global user.name "Daipe Template Creator"
          git config --global user.email "daipe.ai@datasentics.com"
          git config --global init.defaultBranch master

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10'
          architecture: 'x64'

      - name: Setup poetry
        uses: snok/install-poetry@v1.1.1
        with:
          version: 1.1.8

      - name: Replace placeholders
        run: |
          sed -i 's/t__myproject__t/daipe-project/g' pyproject.toml
          sed -i "s/address:.*azuredatabricks.net.*/address: \'[Your workspace address]\'/g" src/$(ls -I daipe.py src)/_config/config_*.yaml
          mv src/__myproject__ src/daipeproject

      - name: Create Feature Store Template
        env:
          TEMPLATE_CREATOR_USERNAME: ${{ secrets.TEMPLATE_CREATOR_USERNAME }}
          TEMPLATE_CREATOR_TOKEN: ${{ secrets.TEMPLATE_CREATOR_TOKEN }}
        run: |
          rm -rf .git
          git init
          git add -- . ':!.github/workflows/create_templates.yml' ':!.vscode/' ':!.idea/'
          git commit -m "Initial commit"
          git remote add origin https://${TEMPLATE_CREATOR_USERNAME}:${TEMPLATE_CREATOR_TOKEN}@github.com/daipe-ai/daipe-template-feature-store.git
          git push origin master --force

      - name: Create Base Template
        env:
          TEMPLATE_CREATOR_USERNAME: ${{ secrets.TEMPLATE_CREATOR_USERNAME }}
          TEMPLATE_CREATOR_TOKEN: ${{ secrets.TEMPLATE_CREATOR_TOKEN }}
        run: |
          sed -i '/feature-store-bundle/d' ./pyproject.toml
          poetry lock --no-update
          poe unify-imports
          git add pyproject.toml poetry.lock src/daipeproject/daipe.py ':!src/daipeproject/_orchestration' ':!src/daipeproject/_config/bundles/featurestorebundle.yaml'
          git commit --amend -m "Initial commit"
          git remote set-url origin https://${TEMPLATE_CREATOR_USERNAME}:${TEMPLATE_CREATOR_TOKEN}@github.com/daipe-ai/daipe-template-base.git
          git push origin master --force
