name: Dev pipeline
on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  build:
    uses: daipe-ai/daipe-project-ci-cd/.github/workflows/build.yml@v1
    with:
      pylint_enabled: true
      check_displays: true
      run_tests: true
