name: Test pipeline
on:
  pull_request:

jobs:
  call-build:
    uses: daipe-ai/skeleton-databricks/.github/workflows/build.yml@master

  call-deploy:
    needs: call-build
    uses: daipe-ai/skeleton-databricks/.github/workflows/deploy.yml@master
    with:
      deploy_command: daipe dbx:repo:update --env=test --repo-url=https://github.com/daipe-ai/skeleton-databricks.git --branch=${{ github.head_ref }} --repo-name=${{ github.head_ref }}
      env: test
    secrets:
      DBX_URL: ${{ secrets.DBX_URL }}
      DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
