name: Test pipeline
on:
  pull_request:

jobs:
  build:
    uses: daipe-ai/daipe-project-ci-cd/.github/workflows/build.yml@v1
    with:
      pylint_enabled: true

  deploy:
    needs: build
    uses: daipe-ai/daipe-project-ci-cd/.github/workflows/run_command.yml@v1
    with:
      command: daipe dbx:repo:update --env=test --repo-url=${{ github.server_url }}/${{ github.repository }}.git --repo-name=${{ github.event.repository.name }} --branch=${{ github.head_ref }} --force
    secrets:
      DBX_TOKEN: ${{ secrets.DBX_TOKEN }}
